apiVersion: v1
kind: Service
metadata:
  labels:
    name: saemea-app
  name: saemea-app-svc
  namespace: tosino
spec:
  type: LoadBalancer
  selector:
    app: saemea-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    #nodePort: 30001
    targetPort: 3000
